spring:
  profiles:
    active: test
  application:
    name: Contact List
  jpa:
    show-sql: false
    database-platform: # Add the dialect here. E.g:  org.hibernate.dialect.OracleSQLDialect
    generate-ddl: false
  datasource:
    url: # Add the database URL here E.g: jdbc:oracle:thin:@localhost:1521:xe
    username: # Add the user name
    password: # Add the password
    driverClassName: # Add the driver class name here

server:
  port: 8090

logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG


